---
- name: Install system dependencies for Cowrie
  apt:
    name:
      - git
      - python3-pip
      - python3-venv
      - libssl-dev
      - libffi-dev
      - build-essential
      - libpython3-dev
      - python3-minimal
      - authbind
      - virtualenv
    state: present
    update_cache: yes
  become: yes

- name: Create cowrie user
  user:
    name: cowrie
    home: /home/cowrie
    shell: /bin/bash
    create_home: yes
  become: yes

- name: Create authbind file for port 22
  file:
    path: /etc/authbind/byport/22
    state: touch
    owner: cowrie
    group: cowrie
    mode: '0770'
  become: yes

- name: Add /home/cowrie/cowrie to git safe.directory
  command: git config --global --add safe.directory /home/cowrie/cowrie
  become: yes
  become_user: root
  changed_when: false

- name: Clone cowrie repo to /home/cowrie/cowrie
  git:
    repo: http://github.com/cowrie/cowrie
    dest: /home/cowrie/cowrie
    version: main
    update: yes
  become: yes

- name: Set ownership of cowrie directory
  file:
    path: /home/cowrie/
    owner: cowrie
    group: cowrie
    recurse: yes
  become: yes

- name: Create Python virtual environment manually
  command: sudo -u cowrie python3 -m venv /home/cowrie/cowrie/cowrie-env
  args:
    creates: /home/cowrie/cowrie/cowrie-env/bin/activate
  become: yes

- name: Upgrade pip in the virtual environment
  pip:
    name: pip
    state: latest
    virtualenv: /home/cowrie/cowrie/cowrie-env
  become: yes

- name: Install Cowrie dependencies from requirements.txt
  pip:
    requirements: /home/cowrie/cowrie/requirements.txt
    virtualenv: /home/cowrie/cowrie/cowrie-env
    virtualenv_python: python3
    state: latest
  become: yes

- name: Set ownership (again) of cowrie directory
  file:
    path: /home/cowrie/
    owner: cowrie
    group: cowrie
    recurse: yes
  become: yes

- name: Copy cowrie.cfg configuration file
  copy:
    src: cowrie.cfg.j2
    dest: /home/cowrie/cowrie/etc/cowrie.cfg
    owner: cowrie
    group: cowrie
    mode: '0644'
  become: yes
  notify:
    - Restart cowrie

- name: Copy cowrie systemd service file
  template:
    src: cowrie.service.j2
    dest: /etc/systemd/system/cowrie.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd
    - Restart cowrie
  become: yes
