---
- name: Install WireGuard
  apt:
    name: wireguard
    state: present

- name: Ensure WireGuard config directory exists
  file:
    path: /etc/wireguard
    state: directory
    mode: '0700'

- name: Generate WireGuard private key if not exists
  command: wg genkey
  register: wg_private_key
  args:
    creates: "{{ wireguard_private_key_path }}"

- name: Save WireGuard private key
  copy:
    content: "{{ wg_private_key.stdout }}"
    dest: "{{ wireguard_private_key_path }}"
    mode: '0600'
  when: wg_private_key is defined

- name: Generate WireGuard public key
  command: wg pubkey
  register: wg_public_key
  args:
    stdin: "{{ wg_private_key.stdout }}"
  when: wg_private_key is defined

- name: Save WireGuard public key
  copy:
    content: "{{ wg_public_key.stdout }}"
    dest: "{{ wireguard_public_key_path }}"
    mode: '0644'
  when: wg_public_key is defined

- name: Deploy WireGuard configuration
  template:
    src: wg0.conf.j2
    dest: "{{ wireguard_config_path }}"
    mode: '0600'

- name: Enable and start WireGuard
  systemd:
    name: "wg-quick@{{ wireguard_interface }}"
    enabled: yes
    state: started
