# roles/wireguard/tasks/main.yml
---
- name: 1. Ensure WireGuard package is installed
  become: yes
  apt:
    name: wireguard
    state: present
  tags: [wireguard]

- name: 2. Ensure WireGuard config directory exists with secure permissions
  become: yes
  file:
    path: /etc/wireguard
    state: directory
    owner: root
    group: root
    mode: '0700'
  tags: [wireguard]

- name: 3. Ensure server private and public keys are generated
  become: yes
  shell: |
    umask 077
    wg genkey | tee /etc/wireguard/server_private.key | wg pubkey > /etc/wireguard/server_public.key
  args:
    creates: /etc/wireguard/server_private.key
  tags: [wireguard]

- name: 4. Ensure WireGuard configuration file is in place from template
  become: yes
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: '0600'
  tags: [wireguard]

- name: 5. Ensure IP forwarding is enabled in the kernel
  become: yes
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes
  tags: [wireguard]

- name: 6. Ensure WireGuard service is active and enabled on boot
  become: yes
  systemd:
    name: wg-quick@wg0
    state: started
    enabled: yes
  tags: [wireguard]
