---
- name: Update APT package cache and upgrade the system
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: dist
  tags: [common, packages]

- name: Install essential security and utility packages
  apt:
    name: "{{ common_packages }}"
    state: present
  tags: [common, packages]

- name: Deploy minimal Fail2Ban configuration
  copy:
    dest: /etc/fail2ban/jail.local
    content: "{{ fail2ban_jail_local }}"
    owner: root
    group: root
    mode: '0644'
  notify: restart fail2ban
  tags: [common, security]

- name: Ensure fail2ban package present (re-check)
  apt:
    name: fail2ban
    state: present
  tags: [common, service]

- name: Ensure fail2ban service is running and enabled
  systemd:
    name: fail2ban
    state: started
    enabled: yes
  tags: [common, service]

- name: Configure and enable UFW rules
  block:
    - name: Ensure UFW is installed
      apt:
        name: ufw
        state: present

    - name: Allow configured UFW rules
      community.general.ufw:
        rule: allow
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
      loop: "{{ ufw_rules }}"
      notify: reload ufw

    - name: Set default UFW policy (enable UFW)
      community.general.ufw:
        state: enabled
        policy: deny
        direction: incoming
      notify: reload ufw
  tags: [common, firewall]
